--trigger for flagging flushing status

CREATE OR REPLACE TRIGGER RPUD.flushingGM_status 
 AFTER INSERT ON RPUD.A80974
 FOR EACH ROW
 BEGIN
	UPDATE RPUD.A71030
	SET RPUD.A71030.ISFLUSHED = 1
	WHERE RPUD.A71030.FACILITYID = :new.FACILITYID;
 END;
 /

CREATE OR REPLACE TRIGGER RPUD.flushingMH_status 
 AFTER INSERT ON RPUD.A81268
 FOR EACH ROW
 BEGIN
	UPDATE RPUD.A71017
	SET RPUD.A71017.ISFLUSHED = 1
	WHERE RPUD.A71017.FACILITYID = :new.FACILITYID;
 END;
 /