CREATE OR REPLACE TRIGGER RPUD.flushing_status 
 AFTER INSERT ON RPUD.A80974
 FOR EACH ROW
 BEGIN
	UPDATE RPUD.A71030
	SET RPUD.A71030.ISFLUSHED = 'Yes'
	WHERE RPUD.A71030.FACILITYID = :new.FACILITYID;
 END;
 /